esphome:
  name: water_flow
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "your_ssid"
  password: "your_password"

logger:

api:

ota:

web_server:
  port: 80

sensor:
  - platform: pulse_meter
    pin: D5
    name: "Ground Well Water Flow Rate"
    unit_of_measurement: "L/min"
    icon: "mdi:water"
    filters:
      - multiply: 0.002096  # 1/477 to convert pulses to liters
    total:
      name: "Ground Well Total Water Usage"
      unit_of_measurement: "L"
      accuracy_decimals: 2
    timeout: 10s
    update_interval: 1s
  
  - platform: pulse_meter
    pin: D6
    name: "PDAM Water Flow Rate"
    unit_of_measurement: "L/min"
    icon: "mdi:water"
    filters:
      - multiply: 0.002096  # 1/477 to convert pulses to liters
    total:
      name: "PDAM Total Water Usage"
      unit_of_measurement: "L"
      accuracy_decimals: 2
    timeout: 10s
    update_interval: 1s